// 各安全域页面的文案集中管理：标题、描述、字段名、空态提示都收口到这里，
// 页面模板不再硬编码文案，便于统一调整、保持一致，也为后续多语言切换预留出口。
export const securityPageContent = {
  // 按页面分块，字段名即页面内使用点，改动这里即可全局生效。
  overview: {
    title: '态势总览',
    description: '集中展示检测任务、高风险态势、默认主链路来源覆盖，以及已落库流量增强结果的趋势与入口边界。',
    badge: '核心展示页',
    summaryTitle: '今日检测概况',
    summaryTextPrefix: '今日新增检测任务：',
    dataScopeText: '来源覆盖展示当前已接入的基础画像、信誉、攻击面来源清单；数字表示覆盖该来源的任务数，未覆盖来源显示 0，未启用来源不展示。',
    sourceCoverage: {
      baseInfoTitle: '基础画像来源覆盖',
      reputationTitle: '信誉来源覆盖',
      attackTitle: '攻击面来源覆盖',
      flowTitle: '流量增强承接',
      empty: '当前暂无可展示的来源统计',
    },
    trendTitle: '任务与预警趋势',
    distributionTitle: '风险等级分布',
    riskTrendTitle: '风险趋势明细',
    flowTrendTitle: '流量增强趋势',
    flowTrendLegend: {
      realMetrics: '窗口聚合已落库',
      entryOnly: '仅承接记录',
      behaviorReady: '行为快照已落库',
      behaviorPending: '行为快照待补全',
    },
    chartEmptyText: '当前暂无足够数据生成图表',
    statLabels: {
      totalTaskCount: '检测任务总数',
      highRiskCount: '高风险任务数',
      criticalRiskCount: '严重风险任务数',
      alertCount: '预警总数',
      exposedTaskCount: '开放端口任务数',
      highRiskPortTasks: '高危端口任务数',
      flowCollectionCount: '近 7 天流量记录',
    },
    riskTrendLabels: {
      date: '日期',
      highRisk: '高风险任务',
      criticalRisk: '严重风险任务',
    },
    flowTrendLabels: {
      date: '日期',
      collectionCount: '承接记录',
      packetCount: '数据包',
      highBehaviorRiskCount: '高行为风险',
      trackedConversationSum: '会话数',
      averageBehaviorRisk: '平均行为分',
      highEntropyPacketCount: '高熵报文',
      averagePortDensity: '平均端口密度',
      directionalBiasCount: '方向偏置天数',
    },
    quickLinks: {
      taskTitle: '进入检测任务',
      taskDescription: '发起新的 IP 检测任务，并查看检测结果与风险评分。',
      alertTitle: '进入预警中心',
      alertDescription: '查看当前预警记录、等级分布与处理状态。',
    },
  },
  task: {
    title: '检测任务',
    description: '发起 IP 检测任务，并查看任务状态、风险评分与关联详情。',
    badge: '任务主入口',
    createCardTitle: '发起检测任务',
    listCardTitle: '任务列表',
    filterTitle: '任务筛选',
    targetIpLabel: '目标 IP / 域名',
    targetIpPlaceholder: '请输入待检测 IP 地址或域名',
    filterIpPlaceholder: '按目标 IP 筛选',
    statusPlaceholder: '按任务状态筛选',
    riskLevelPlaceholder: '按风险等级筛选',
    sortPlaceholder: '按排序规则查看',
    submitButton: '发起检测',
    filterButton: '查询',
    resetButton: '重置',
    activeFilterPrefix: '当前筛选条件：',
    noFilterText: '未设置筛选条件',
    quickStats: {
      total: '当前结果总数',
      highRisk: '高风险任务',
      criticalRisk: '严重风险任务',
      failed: '执行失败任务',
    },
    emptyText: '当前筛选条件下没有任务记录',
    createSuccess: '检测任务创建成功',
    createWarning: '目标 IP 不能为空',
    createInvalidWarning: '目标输入格式不合法，请输入 IP 地址或域名',
    readonlyHint: '当前角色仅可查看任务信息，不能发起检测任务。',
    columns: {
      taskId: '任务编号',
      taskNo: '任务单号',
      targetIp: '目标 IP',
      riskLevel: '风险等级',
      taskStatus: '任务状态',
      scoreValue: '评分值',
      createdAt: '创建时间',
      action: '操作',
    },
    detailAction: '查看详情',
  },
  taskDetail: {
    title: '任务详情',
    description: '查看任务基础信息、默认主链路来源、真实流量承接结果、原型入口状态、证据链、评分因子以及关联预警情况。',
    backButton: '返回任务列表',
    notFound: '记录不存在或已删除',
    sections: {
      basic: '任务基本信息',
      baseInfo: 'IP 基础画像',
      score: '来源、证据与评分结果',
      flow: '流量增强结果',
      alert: '关联预警摘要',
    },
    labels: {
      errorMessage: '失败原因',
    },
    empty: {
      baseInfo: '当前任务暂无基础画像数据',
      score: '当前任务暂无特征或评分结果',
      flow: '当前任务未落库流量增强结果',
      alert: '该任务当前未触发预警',
    },
    flowLabels: {
      realMetrics: '真实已落地字段',
      signals: '协议与动态信号',
      runtimeContext: '运行上下文',
      entryFields: '入口状态字段',
      traceability: '追溯承接',
      collectionHistory: '采集历史',
      evidenceTimeline: '窗口级证据时间线',
      trend: '窗口级趋势',
      rawPayload: '原始承接载荷',
    },
  },
  history: {
    title: '检测历史',
    description: '基于统一历史记录接口展示任务与预警事件时间线，并补充流量摘要、真实指标概览与任务详情追溯入口。',
    badge: '统一历史视图',
    typeFilter: {
      all: '全部事件',
      task: '检测任务',
      alert: '预警事件',
    },
    searchPlaceholder: '按目标 IP 或任务单号筛选历史记录',
    empty: '当前没有可展示的历史事件记录',
    columns: {
      title: '事件标题',
      eventType: '事件类型',
      targetIp: '目标 IP',
      originalTarget: '原始输入',
      taskNo: '任务单号',
      sourceSummary: '来源链摘要',
      flowSummary: '流量摘要',
      flowTrace: '追溯状态',
      level: '风险等级',
      status: '状态',
      time: '发生时间',
      action: '操作',
    },
    detailAction: '查看详情',
  },
  alert: {
    title: '预警中心',
    description: '展示系统触发的预警记录，并支持查看预警详情、关联任务和评分信息。',
    badge: '预警处理入口',
    listCardTitle: '预警列表',
    filterIpPlaceholder: '按目标 IP 筛选',
    levelPlaceholder: '按预警等级筛选',
    sendStatusPlaceholder: '按发送状态筛选',
    filterButton: '查询',
    resetButton: '重置',
    activeFilterPrefix: '当前筛选条件：',
    noFilterText: '未设置筛选条件',
    quickStats: {
      total: '当前结果总数',
      critical: '严重预警',
      high: '高风险预警',
      failed: '发送失败',
    },
    emptyText: '当前筛选条件下没有预警记录',
    columns: {
      alertId: '预警编号',
      taskNo: '任务单号',
      targetIp: '目标 IP',
      alertLevel: '预警等级',
      channel: '通知渠道',
      sendStatus: '发送状态',
      createdAt: '创建时间',
      action: '操作',
    },
    detailAction: '查看详情',
  },
  alertDetail: {
    title: '预警详情',
    description: '查看预警主体信息、关联任务执行状态以及对应评分结果。',
    backButton: '返回预警列表',
    notFound: '记录不存在或已删除',
    sections: {
      basic: '预警主体信息',
      task: '关联任务信息',
      score: '关联评分信息',
    },
    empty: {
      task: '当前预警暂无关联任务信息',
      score: '当前预警暂无关联评分信息',
    },
  },
  config: {
    title: '系统配置',
    description: '维护评分权重、风险阈值、通知渠道以及特征源配置，使评分逻辑具备可配置能力。',
    badge: '课题配置中心',
    readonlyHint: '当前角色仅可查看配置，不能执行修改操作。',
    loadError: '配置加载失败',
    saveSuccess: '配置保存成功',
    saveButton: '保存配置',
    sourceTitle: '特征源配置',
    thresholdTitle: '风险阈值配置',
    weightTitle: '评分权重配置',
    fields: {
      whoisEndpoint: 'WHOIS 数据源',
      reputationEndpoint: '信誉数据源',
      attackSurfaceEndpoint: '攻击面数据源',
      flowEnabled: '流量增强开关',
      flowMode: '流量模式',
      flowInterfaceName: '在线抓包网卡',
      flowPcapFilePath: '离线 PCAP 路径',
      flowSampleProfile: '样本画像',
      flowWindowSeconds: '流量窗口秒数',
      flowTimeoutSeconds: '流量超时秒数',
      notifyChannel: '默认通知渠道',
      highRiskThreshold: '高风险阈值',
      criticalRiskThreshold: '严重风险阈值',
      whoisWeight: 'WHOIS 权重',
      reputationWeight: '信誉权重',
      attackSurfaceWeight: '攻击面权重',
      behaviorWeight: '行为权重',
    },
    sourceSelectHint: '点击下拉框选择数据源；选中项会以标签形式显示在输入框中，可直接移除。',
  },
}
